name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v5

            - name: Setup do Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'

            - name: Install dependencies
              working-directory: ./src
              run: 
                python -m pip install --upgrade pip
                pip -r requirements.txt

            - name: Install dependencies
              working-directory: ./src
              run: 
                python -m pytest tests/ -v

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push docker image
              uses: docker/build-push-action@v5
              with:
                context: ./src
                file: ./src/Dockerfile
                push: true
                tags: 
                  -t lucassis/encontros-tech:latest
                  -t lucassis/encontros-tech:v${{ github.run_number }}

    CD:
        runs-on: ubuntu-latest
        needs: [CI]
        steps:
            - run: echo "Obter o código"
            - run: echo "Configurar o Kubeconfig"
            - run: echo "Executar o apply"
